apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  replicas: 3
  selector:
    matchLabels:
        app: http
        tier: frontend
  template:
    metadata:
      labels:
        app: http
        tier: frontend
    spec:
      containers:
      - name: http
        image: http
        env:
        - name: GET_HOSTS_FROM
          value: "dns"
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
        ports:
        - containerPort: 80
---
