apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  replicas: 3
  selector:
    matchLabels:
        app: http
  template:
    metadata:
      labels:
        app: http
    spec:
      containers:
      - name: http
        image: billiardyoda/http:v1
        ports:
        - containerPort: 80
