apiVersion: apps/v1
kind: Deployment
metadata:
  name: http
spec:
  selector:
    matchLabels:
      run: http
  replicas: 1
  template:
    metadata:
      labels:
        run: http
    spec:
      containers:
      - name: http
        image: billiardyoda/http
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 500m
          requests:
            cpu: 200m
---
apiVersion: v1
kind: Service
metadata:
  name: http
  labels:
    run: http
spec:
  ports:
  - port: 80
  selector:
    run: http
